import { GoogleGenAI } from "@google/genai";
import { ModelType, GenerateConfig } from "../types";

export async function generateLogoMockup(
  mockupBase64: string,
  logoBase64: string,
  area: { x: number; y: number; w: number; h: number },
  config: GenerateConfig,
  customApiKey?: string
) {
  const apiKey = customApiKey || (process.env.GEMINI_API_KEY as string);
  
  if (!apiKey) {
    throw new Error("Missing Gemini API Key. Please provide one in the settings.");
  }

  const ai = new GoogleGenAI({ apiKey });
  const model = config.model;

  const prompt = `
    I have a mockup image part of a product and a logo. 
    Your task is to place the provided logo onto the mockup image.
    The logo should be placed within this specific area: 
    X: ${area.x}px, Y: ${area.y}px, Width: ${area.w}px, Height: ${area.h}px 
    relative to the mockup image size.
    
    Ensure the logo:
    1. Matches the perspective, curves, and surface texture of the mockup.
    2. Adjusts to the lighting and shadows of the scene.
    3. Looks like a real, physical print or sticker on the product.
    
    Output ONLY the final merged image.
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: mockupBase64,
              mimeType: "image/png",
            },
          },
          {
            inlineData: {
              data: logoBase64,
              mimeType: "image/png",
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: config.aspectRatio,
          imageSize: config.quality,
        },
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Gemini Mockup Error:", error);
    throw error;
  }
}
